import "@/public/styles/globals.css";
import { CookiesConstant } from "@/utils/constants";
import AuthProvider from "@/utils/providers/auth-provider";
import clsx from "clsx";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { cookies } from "next/headers";
import { ToastContainer } from "react-toastify";
import ThemeRegistry from "../utils/providers/theme-register";
import NprogressProvider from "@/utils/providers/nprogress-provider";
import ReduxProvider from "@/utils/providers/redux-provider";
const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin", "vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const accessToken = cookieStore.get(CookiesConstant.accessToken);
  const refreshToken = cookieStore.get(CookiesConstant.refreshToken);
  return (
    <html lang="en">
      <body className={clsx(roboto.className, "h-screen")}>
        <ReduxProvider>
          <ThemeRegistry options={{ key: "mui" }}>
            <NprogressProvider>
              <AuthProvider
                initialAccessToken={{
                  accessToken: accessToken?.value,
                  refreshToken: refreshToken?.value,
                }}
              >
                {children}
                <ToastContainer />
              </AuthProvider>
            </NprogressProvider>
          </ThemeRegistry>
        </ReduxProvider>
      </body>
    </html>
  );
}
